// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: add_post.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, title, created_at, updated_at, url, description, feed_id, published_at) 
VALUES (DEFAULT, $1, DEFAULT, DEFAULT, $2, $3, $4, $5) 
RETURNING id, created_at, updated_at, title, url, description, feed_id, published_at
`

type CreatePostParams struct {
	Title       sql.NullString
	Url         string
	Description sql.NullString
	FeedID      uuid.UUID
	PublishedAt sql.NullTime
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.FeedID,
		arg.PublishedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.FeedID,
		&i.PublishedAt,
	)
	return i, err
}
