// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_post.sql

package database

import (
	"context"
)

const getPost = `-- name: GetPost :one
SELECT id, created_at, updated_at, title, url, description, feed_id, published_at FROM posts
WHERE url = $1 LIMIT 1
`

func (q *Queries) GetPost(ctx context.Context, url string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, url)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.FeedID,
		&i.PublishedAt,
	)
	return i, err
}
