// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_posts_for_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUsersFeedPosts = `-- name: GetUsersFeedPosts :many
SELECT id, created_at, updated_at, title, url, description, feed_id, published_at FROM posts
WHERE feed_id IN (
    SELECT feed_id FROM feed_follows
    WHERE user_id = $1
)
ORDER BY published_at DESC NULLS LAST
LIMIT $2
`

type GetUsersFeedPostsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) GetUsersFeedPosts(ctx context.Context, arg GetUsersFeedPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getUsersFeedPosts, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.FeedID,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
